### PR TITLE
feat(relay): allow relaying from other docker containers

### PR DESCRIPTION
**Pull request by DrMurx**
Allow to relay other containers by just adding the IP ranges docker uses for its internal networking,

TODO:
* ~~Update README~~
* ~~Make it use a environment variable (more general approach)~~

### CODE REVIEW

**Comment by hardware** [comment]
Allow relaying from other docker containers **must** be an **explicit** action by the mailserver administrator, i can not accept 3 larges ranges by default, even if they are in private IPv4 address spaces.

```bash
# /mnt/docker/mail/postfix/custom.conf

mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 docker-container-IP/32, docker-container-RANGE/24...
```

**Comment by DrMurx** [comment]
Totally aware of. That's why I put a remark in the TODO. Will follow up on that and make it configurable.

**Comment by DrMurx** [comment]
PR is updated.

**Comment by DrMurx** [comment]
Do you think the warning about the open relay is clear enough? 

We could also grep for `/0` in the `RELAY_NETWORKS` variable (and in the files it might point to) and bail out with an error.

**Comment by hardware** [comment]
Yeah i think it's clear enough, i assume that someone who use the `RELAY_NETWORKS` variable know what he is doing.

Thanks for this PR !

**Comment by DrMurx** [comment]
@ksylvan It should be sufficient.

The default policy of `smtp_sender_restrictions` is `allow`, and the current configuration only names a few restrictions which don't apply (at least for most sane services).

The other configuration option controlling the relaying is `smtpd_relay_restrictions` which already includes `permit_mynetworks`.

**Comment by ksylvan** [comment]
That's interesting. I'll try that in my setup.

**Pull request merged**
