### PR TITLE
simplification

### PR DESCRIPTION
**Pull request by scones**
debugging my own postfix installation i came across this commit:
https://github.com/hardware/mailserver/commit/c2c8a22fe860beafd46603e6ef779cc7aa164a8a

as i already had a SO-answer for that open, which actually avoided installing more stuff, i thought i'd share.

this is untested tho; i don't use your stack.

take and try it AS IS.

### CODE REVIEW

**Comment by sknight80** [comment]
Great PR. We need to update one of the unit test due to the DIG command is not available. See the Travis log.

**Comment by scones** [comment]
let's see if this works..

**Comment by hardware** [comment]
@scones This PR breaks clamav-unofficial-sigs.sh both dig and host commands are required, and you forgot about MariaDB host search too.

**Comment by scones** [comment]
ah, github-repo-search has betrayed me yet again!

well, you may want to keep getent in mind for future development as a replacement for dig, thus reducing image size.

best regads,
scones

**Pull request closed without merging**
