### PR TITLE
fix rerunning config compilation scripts

### PR DESCRIPTION
**Pull request by Matchlighter**
## Description

Fixes issues with the setup portion of runtime script rerunning after a `docker stop` and `docker start`. This was not causing serious issues, but raised a few concerns, especially in re-appending content to config files in a couple of places.

Also refactors the setup portion to a separate script for clarity and separation of concerns.

Precursor to `feature-certwatch` of my fork. It's a feature that I'll use, but it may be considered out-of-scope for this project, so I'll let you consider that separately.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (a change that neither fixes a bug nor adds a feature)

## Status

- [x] Ready
- [ ] Testing
- [ ] Development

## How has this been tested ?

- [x] `$ make`
- [x] Ran the image multiple times, verified that `setup.sh` was not rerun after restarting a container.

### CODE REVIEW

**Comment by hardware** [comment]
Nice refactor, I'll digging your work. Can you describe all the changes you made ? Because git diff tool does not clearly show all the modifications in a 1:1 way.

Besides, your pull request breaks a lot of tests. Did you test this in production ?

**Comment by hardware** [comment]
Can you split this pull request into several commit ? 

First commit -> run.sh file split
Second commit -> code changes inside files

**Comment by Matchlighter** [comment]
I got pulled into other projects so I haven't been able to deploy or migrate our current mailserver. I'll update it and split the commits when I get a chance (over the holidays, if not sooner), as well as dig into the tests - I was having troubles with some of them pre- and post- and assumed they weren't all current.

**Comment by PeerD** [comment]
So what is the status of this PR? Me and some others in #347 are waiting for this PR to be merged so I can continue my work on LDAP support for this project. From what it sounds like, it should be (almost?) ready?

**Comment by hardware** [comment]
@PeerD Sorry, I'm running out of time to maintain this docker image and review pull requests right now. I think I'm going to need another maintainer. Maybe I will make a call to the volunteers in regular members like @navossoc @denji @DrMurx or someone who has a good knowledge of this project.

3 years ago it was only a small personal project 😄 

I will try to watch this at the end of the week.

**Comment by Matchlighter** [comment]
I think this is good to go. I've had it out for a while now and have had some chances to test and make sure it's working right.

**Pull request merged**
