### PR TITLE
Add IPv6 NAT support.

### PR DESCRIPTION
**Pull request by navossoc**
## Description

Add IPv6 NAT support.
Helps to solve IPv6 network problems like identifying the real ip address of connections through IPv6.

Fixes # (issue)
https://github.com/hardware/mailserver/issues/221

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Status

- [X] Ready

## Todo List
- [X] Documentation

## How has this been tested ?

I'm currently running this for 20 days, no issues so far.

- IPv4 connection:

**Example**
`telnet your_server_ipv4 587`
`telnet 104.131.xxx.xxx 25`

**Expected**

```plain
mailserver      | 2018-04-08T02:50:12.073149+00:00 mail postfix/submission/smtpd[625]: connect from unknown[186.214.xxx.xxx]
mailserver      | 2018-04-08T02:50:12.357745+00:00 mail postfix/submission/smtpd[625]: lost connection after CONNECT from unknown[186.214.xxx.xxx]
mailserver      | 2018-04-08T02:50:12.357854+00:00 mail postfix/submission/smtpd[625]: disconnect from unknown[186.214.xxx.xxx] commands=0/0
```

- IPv6 connection:

**Example**
`telnet your_server_ipv6 587`
`telnet 2604:a880:800:10::xxx:xxxx 587`

**Expected**

```plain
mailserver      | 2018-04-08T02:50:15.558027+00:00 mail postfix/submission/smtpd[625]: connect from unknown[2804:7f1:4080:d3a2:xxxx:xxxx:xxxx:xxxx]
mailserver      | 2018-04-08T02:50:16.813053+00:00 mail postfix/submission/smtpd[625]: lost connection after CONNECT from unknown[2804:7f1:4080:d3a2:xxxx:xxxx:xxxx:xxxx]
mailserver      | 2018-04-08T02:50:16.813152+00:00 mail postfix/submission/smtpd[625]: disconnect from unknown[2804:7f1:4080:d3a2:xxxx:xxxx:xxxx:xxxx] commands=0/0
```

You can check your logs with:

`docker-compose logs -f mailserver`
or
`docker logs -f mailserver`

If it is working properly you will see the REAL ip address from your client on the IPv6 test.

Like this:
> mailserver      | 2018-04-08T02:50:15.558027+00:00 mail postfix/submission/smtpd[625]: connect from **unknown[2804:7f1:4080:d3a2:xxxx:xxxx:xxxx:xxxx]**

If IPv6nat is not enable, you will see something like this:
> mailserver      | 2018-04-08T02:50:12.073149+00:00 mail postfix/submission/smtpd[625]: connect from **unknown[172.18.xxx.xxx]**

### CODE REVIEW

**Comment by denji** [comment]
Maybe better comment `ipv6nat` service-section by default?

It's not like a pretty stable solution enable by default.

**Comment by navossoc** [comment]
> Maybe better comment ipv6nat service-section by default?

Maybe... I don't know what approach @hardware want to take.
Should we create a wiki to document it? Add a comment on the README.md? I don't know.

I'm just trying show an example of how to add it.

> It's not like a pretty stable solution enable by default.

Why did you say that?

[]'s

**Comment by hardware** [comment]
Thanks for taking time to document this :)

> Maybe... I don't know what approach @hardware want to take.
Should we create a wiki to document it? Add a comment on the README.md ?

I prefer it to be added in the readme.

And with this on top of docker-compose.yml : 

```yml
version: "3"

# IPv4 network
# docker network create http_network

# IPv4/IPv6 network
# docker network create http_network --ipv6 --subnet "fd00:0000:0000:0000::/64"
# More information here: https://github.com/hardware/mailserver#ipv6-nat

networks:
  http_network:
    external: true
  mail_network:
    external: false
```

**Comment by hardware** [comment]
There any progress on this ?

**Comment by navossoc** [comment]
Done, please take a look.

Feel free to edit.

**Comment by hardware** [comment]
Perfect, thanks !

**Pull request merged**
