### PR TITLE
deprecate TLS 1.0

### PR DESCRIPTION
**Pull request by reichley**
deprecate use of TLS 1.0 (could almost also deprecate 1.1 at this point)

Thanks for submitting a pull request ! Please provide enough information so that others can review your changes. 

For more information, see the `CONTRIBUTING` guide.

## Description

Deprecate use of TLS 1.0 (postfix). Hasn't been updated in years and proved susceptible to POODLE and BEAST attacks in past.

Fixes # (issue)

Postfix currently uses all versions of TLS. Postfix, after implemention, would only use TLS 1.1 and 1.2

## Type of change
- [x] Performance improvement
- [x] Refactoring (a change that neither fixes a bug nor adds a feature)

## Status

- [x] Ready

## Todo List
- [x] Implementation

## How has this been tested ?

Added to [postfix config override](https://github.com/hardware/mailserver#override-postfix-configuration) and tested by sending/receiving mail with several domains and different smtp servers. Also ran tests on htbridge.com (mymailserver.email:25)
- [x] Test A
- [x] Test B

### CODE REVIEW

**Comment by 1n5aN1aC** [comment]
Are there any stats on SSL/TLS support for mailservers?

There's good stats out there for HTTPS, but I fear that mailservers are significantly less updated, and this change risks having legitimate emails rejected from domains if that is the case.

In any case, I'm all for disabling it, but some stats on version compatibility would make me more confident.

**Comment by hardware** [comment]
Looks good to me, TLS 1.0 must be disabled in 2018.

Explicitly listing the protocols to include, rather than protocols to exclude, is supported, but not recommended by postfix developers.

You should use this syntax instead :

```
smtp_tls_protocols = !SSLv2,!SSLv3,!TLSv1
smtp_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1
smtpd_tls_protocols = !SSLv2,!SSLv3,!TLSv1
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1
```

And for Dovecot : 

```
ssl_protocols = !SSLv3,!TLSv1
```

**Comment by navossoc** [comment]
I agree with @hardware, it is easy to negate.

What about traefik?
https://docs.traefik.io/configuration/entrypoints/

```toml
[entryPoints.http.tls]
  minVersion = "VersionTLS11"
```

Should do the trick.

**Comment by hardware** [comment]
I think for web traffic, we can safely use only TLSv1.2+

```
minVersion = "VersionTLS12"
```

https://caniuse.com/#feat=tls1-2

And this ciphers suite : 

```
cipherSuites = [
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
]
```

**Comment by reichley** [comment]
Thanks for the pointers, @hardware and @navossoc. I've corrected edits made to the postfix config and edited the respective dovecot and traefik files.

**Comment by 1n5aN1aC** [comment]
As a comment, if we're requiring tls1.2 for web traffic, we can remove two of those cipers, and have a bit better theoretical security.

The last two (`"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"` and `"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"`) aren't even supported within TLS1.2, so might as well remove them, and gain a bit of resilience against potential downgrade attacks, without losing any compatibility.

**Comment by reichley** [comment]
@1n5aN1aC, where'd you find that 1.2 doesn't use those ciphers? I ran my site (mailserver traefik page) against both ssllabs.com/ssltest and htbridge.com/ssl and both listed the two ciphers under TLS1.2...

**Comment by hardware** [comment]
> The last two ("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA" and "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA") aren't even supported within TLS1.2.

This is not true, look at table above. You can check cipher compatibility with https://tls.imirhil.fr/

**Comment by 1n5aN1aC** [comment]
@reichley @hardware you are both correct.  I had a miss-configuration that was causing the ciphers to only show up under tls1.1 on ssllabs.  I have corrected that and you are indeed correct.

Sorry.

**Comment by denji** [comment]
@hardware ECDSA containous/traefik#2940, containous/traefik#3319

**Comment by navossoc** [comment]
I'm having some issues with this update.

Later I can post more details, first I need to collect more data.
Probably I will need to revert this change.

**Comment by navossoc** [comment]
Well, this is just a sample of what I got:
```
2018-07-17T19:06:55.799756+00:00 mail-nyc3 postfix/smtpd[3217]: connect from 66-220-144-150.mail-mail.facebook.com[66.220.144.150]
2018-07-17T19:06:56.214877+00:00 mail-nyc3 postfix/smtpd[3217]: SSL_accept error from 66-220-144-150.mail-mail.facebook.com[66.220.144.150]: -1
2018-07-17T19:06:56.215219+00:00 mail-nyc3 postfix/smtpd[3217]: warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974:
2018-07-17T19:06:56.215581+00:00 mail-nyc3 postfix/smtpd[3217]: lost connection after STARTTLS from 66-220-144-150.mail-mail.facebook.com[66.220.144.150]
2018-07-17T19:06:56.215853+00:00 mail-nyc3 postfix/smtpd[3217]: disconnect from 66-220-144-150.mail-mail.facebook.com[66.220.144.150] ehlo=1 starttls=0/1 commands=1/2
```

Here is a list of some domains that could not send me emails, some are spam, but a few are legit.
```
66-220-144-143.mail-mail.facebook.com[66.220.144.143]
66-220-144-144.mail-mail.facebook.com[66.220.144.144]
66-220-144-145.mail-mail.facebook.com[66.220.144.145]
66-220-144-146.mail-mail.facebook.com[66.220.144.146]
66-220-144-147.mail-mail.facebook.com[66.220.144.147]
66-220-144-148.mail-mail.facebook.com[66.220.144.148]
66-220-144-149.mail-mail.facebook.com[66.220.144.149]
66-220-144-150.mail-mail.facebook.com[66.220.144.150]
66-220-155-135.mail-mail.facebook.com[66.220.155.135]
66-220-155-136.mail-mail.facebook.com[66.220.155.136]
66-220-155-137.mail-mail.facebook.com[66.220.155.137]
66-220-155-138.mail-mail.facebook.com[66.220.155.138]
66-220-155-139.mail-mail.facebook.com[66.220.155.139]
66-220-155-140.mail-mail.facebook.com[66.220.155.140]
66-220-155-141.mail-mail.facebook.com[66.220.155.141]
66-220-155-142.mail-mail.facebook.com[66.220.155.142]
66-220-155-143.mail-mail.facebook.com[66.220.155.143]
66-220-155-144.mail-mail.facebook.com[66.220.155.144]
66-220-155-145.mail-mail.facebook.com[66.220.155.145]
66-220-155-146.mail-mail.facebook.com[66.220.155.146]
66-220-155-147.mail-mail.facebook.com[66.220.155.147]
66-220-155-148.mail-mail.facebook.com[66.220.155.148]
66-220-155-149.mail-mail.facebook.com[66.220.155.149]
66-220-155-150.mail-mail.facebook.com[66.220.155.150]
66-220-155-151.mail-mail.facebook.com[66.220.155.151]
66-220-155-152.mail-mail.facebook.com[66.220.155.152]
66-220-155-153.mail-mail.facebook.com[66.220.155.153]
66-220-155-154.mail-mail.facebook.com[66.220.155.154]
66-220-155-155.mail-mail.facebook.com[66.220.155.155]
66-220-155-156.mail-mail.facebook.com[66.220.155.156]
66-220-155-157.mail-mail.facebook.com[66.220.155.157]
66-220-155-158.mail-mail.facebook.com[66.220.155.158]
69-171-232-128.mail-mail.facebook.com[69.171.232.128]
69-171-232-129.mail-mail.facebook.com[69.171.232.129]
69-171-232-130.mail-mail.facebook.com[69.171.232.130]
69-171-232-131.mail-mail.facebook.com[69.171.232.131]
69-171-232-132.mail-mail.facebook.com[69.171.232.132]
69-171-232-133.mail-mail.facebook.com[69.171.232.133]
69-171-232-134.mail-mail.facebook.com[69.171.232.134]
69-171-232-135.mail-mail.facebook.com[69.171.232.135]
69-171-232-136.mail-mail.facebook.com[69.171.232.136]
69-171-232-137.mail-mail.facebook.com[69.171.232.137]
69-171-232-138.mail-mail.facebook.com[69.171.232.138]
69-171-232-139.mail-mail.facebook.com[69.171.232.139]
69-171-232-140.mail-mail.facebook.com[69.171.232.140]
69-171-232-141.mail-mail.facebook.com[69.171.232.141]
69-171-232-142.mail-mail.facebook.com[69.171.232.142]
69-171-232-143.mail-mail.facebook.com[69.171.232.143]
69-171-232-144.mail-mail.facebook.com[69.171.232.144]
69-171-232-145.mail-mail.facebook.com[69.171.232.145]
69-171-232-146.mail-mail.facebook.com[69.171.232.146]
69-171-232-147.mail-mail.facebook.com[69.171.232.147]
69-171-232-148.mail-mail.facebook.com[69.171.232.148]
69-171-232-149.mail-mail.facebook.com[69.171.232.149]
69-171-232-150.mail-mail.facebook.com[69.171.232.150]
69-171-232-151.mail-mail.facebook.com[69.171.232.151]
a2-smithers2.uhserver.com[200.147.32.42]
a2-smithers3.uhserver.com[200.147.32.43]
a2-smithers4.uhserver.com[200.147.32.40]
a2-smithers5-1.uhserver.com[200.147.35.76]
a2-smithers5-2.uhserver.com[200.147.35.78]
a2-socom3-1.uol.com.br[200.147.34.34]
a2-socom9-2.uol.com.br[200.147.34.51]
bn162.mta.exacttarget.com[199.122.120.162]
bv167.mta.exacttarget.com[198.245.84.167]
cliente3.email.ekonomizador.com.br[51.255.11.212]
cupom-104.cupomemail.com[144.217.170.179]
cupom-105.meucupommail.com[144.217.231.148]
cupom-106.cupomemail.com[144.217.170.181]
cupom-107.meucupommail.com[144.217.231.150]
d18bc8bc72e0994d45510bc5199d2a130.blackdelist.com.br[177.93.107.130]
d18bc8bc72e0994d45510bc5199d2a140.blackdelist.com.br[177.93.107.140]
d18bc8bc72e0994d45510bc5199d2a141.blackdelist.com.br[177.93.107.141]
d18bc8bc72e0994d45510bc5199d2a142.blackdelist.com.br[177.93.107.142]
d18bc8bc72e0994d45510bc5199d2a153.blackdelist.com.br[177.93.107.153]
d18bc8bc72e0994d45510bc5199d2a154.blackdelist.com.br[177.93.107.154]
d18bc8bc72e0994d45510bc5199d2a166.blackdelist.com.br[177.93.107.166]
d18bc8bc72e0994d45510bc5199d2a167.blackdelist.com.br[177.93.107.167]
d18bc8bc72e0994d45510bc5199d2a176.blackdelist.com.br[177.93.107.176]
d18bc8bc72e0994d45510bc5199d2a177.blackdelist.com.br[177.93.107.177]
d18bc8bc72e0994d45510bc5199d2a178.blackdelist.com.br[177.93.107.178]
d18bc8bc72e0994d45510bc5199d2a180.blackdelist.com.br[177.93.107.180]
descontos-105.descontosmail.com[144.217.231.180]
descontos-114.descontosmail.com[144.217.231.189]
email-110.emailespecial.net[167.114.203.9]
ev-131.rp.enviou.net.br[187.108.202.183]
mail.barreds.com.br[189.8.79.137]
mail.hdi-gerling.com.br[200.155.104.76]
mail.hdigerling.com.br[200.155.104.76]
mail2.hdi.com.br[200.155.104.76]
mrb99-191-103.lupadedescontos.com.br[192.99.191.103]
mrb99-191-104.lupadedescontos.com.br[192.99.191.104]
mrb99-191-105.lupadedescontos.com.br[192.99.191.105]
mrb99-191-61.lupadedescontos.com.br[192.99.191.61]
mrb99-191-62.lupadedescontos.com.br[192.99.191.62]
mta04.smpt.ekonomizador.com.br[51.255.11.217]
mta1.lmn1.cupomsivo.com.br[63.143.35.50]
mta2.lmn1.cupomsivo.com.br[63.143.35.51]
mta4.lmn1.cupomsivo.com.br[63.143.35.53]
mx65-omc2s139.ascoisa.com.br[79.142.65.139]
mx65-omc2s140.ascoisa.com.br[79.142.65.140]
mx65-omc2s141.ascoisa.com.br[79.142.65.141]
nav4l3.garantaseucupom.com.br[216.245.216.197]
nav4l4.garantaseucupom.com.br[216.245.216.198]
nav4l8.garantaseucupom.com.br[216.245.216.202]
nav4l9.garantaseucupom.com.br[216.245.216.203]
poup-104.poupcupons.com[144.217.231.163]
poup-108.poupcupons.com[144.217.231.167]
poup-114.poupmail.com.br[144.217.33.77]
roxinol83.valecupom.com[216.245.195.183]
shop-111.e-mail-shop.com[192.95.44.106]
smtp2.bradseg.com.br[200.218.160.159]
smtp21.shopback.com.br[52.10.103.127]
srvdct204a.dctcomercial.com.br[177.47.103.204]
srvdct205a.dctcomercial.com.br[177.47.103.205]
unknown[177.136.40.102]
vesta.instemaqvendas.com.br[206.189.184.179]
wnh0.wnhs.com.br[164.132.197.207]
wnh2.wnhs.com.br[164.132.241.12]
```

For now I will not deprecate TLS 1.0.

PS: I don't any data about outbound emails because I didn't apply this change on my mail relay.
PS2: Also got some issues with `STARTTLS` with PHPMailer, not sure which version now.

**Comment by hardware** [comment]
I think we should make it customizable with environment variables, like a TLS_LEVEL set to `modern` by default (TLSv1.1 and TLSv1.2) but also with an `intermediate` compatibility mode.

```yml
environment:
  TLS_LEVEL=intermediate # Enables TLSv1, TLSv1.1 and TLSv1.2
```

**Comment by navossoc** [comment]
Looks good to me...

Another configuration issue I found:
Windows 7 SP1 + Office 2016 will not work.

You need to enable TLS 1.1 and TLS 1.2 on Windows registry.

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"DisabledByDefault"=dword:00000000
```

**Pull request merged**
