### PR TITLE
Fixed spelling/typos in Readme

### PR DESCRIPTION
**Pull request by atomtigerzoo**
## Description

Fixes some typos and spelling mistakes inside the Readme.

## Type of change

- [X] Documentation only

## Status

- [X] Ready

### CODE REVIEW

**Comment by sknight80** [comment]
It looks like the merged pull request broke Travis CI.  Could you fix it?

**Comment by atomtigerzoo** [comment]
Hi @sknight80 - I think the build failed/was broken before, as you can see in the original Readme on the frontpage of this repo. I just edited `Readme.md` and I hope that everything in there won't break the automatic build.

**Comment by hardware** [comment]
> It looks like the merged pull request broke Travis CI.

Nope, something broke before this PR. Dozens tests are broken now, since the last base update. I don't have time to look that atm.

**Review by sknight80 — APPROVED** [review]
LGTM. Let us roll the ball forward.

**Pull request closed without merging**
