### PR TITLE
Add docker secret support for passwords

### PR DESCRIPTION
**Pull request by amq**
We first check if `DBPASS` is an existing file if so, we read the file contents into the same variable, if not, we keep the original value.

**Example usage**

1. Create a secret on the swarm mode manager node:

```sh
echo "password" | docker secret create mailserver_dbpass -
```

2. Specify the secret location as `DBPASS` in `docker-compose.yml`:
```
services:
  mailserver:
    environment:
      - DBPASS=/run/secrets/mailserver_dbpass
    secrets:
      - mailserver_dbpass

secrets:
  mailserver_dbpass:
    external: true
```

The same applies to `REDIS_PASS` and `RSPAMD_PASSWORD`.

The main idea is to avoid storing the plain-text passwords in `docker-compose.yml`. More about Docker Secrets: https://docs.docker.com/engine/swarm/secrets/

If this PR gets accepted, we'll need to make a similar change in `hardware/postfixadmin`. Note that `mariadb` already [supports](https://github.com/docker-library/mariadb/commit/6452a881b90283f46c88925b08c2d580a49a27cc) `MYSQL_ROOT_PASSWORD_FILE`, while `redis` does [not yet](https://github.com/docker-library/redis/issues/46).

### CODE REVIEW

**Comment by amq** [comment]
Travis failed because of some unrelated `clamav` problem. Similarly with the first commit.

**Comment by hardware** [comment]
Thanks for this PR. Can you use the originals variables for this purpose and not create new ones, like this :

`DBPASS=$([ -f $DBPASS ] && cat $DBPASS_FILE || echo ${DBPASS:-})`

**Comment by amq** [comment]
@hardware done.

**Comment by vizv** [comment]
I don't like the idea about `env_file` added by https://github.com/docker-library/mariadb/commit/6452a881b90283f46c88925b08c2d580a49a27cc.

For me, I create an `init.sh`:

```bash
#!/bin/sh
[ -f '/.env' ] && export $(cat '/.env' | grep -v '^#\|^$' | xargs)
exec "$@"
```

And have my compose-file like this:

```yml
version: '3.3'
...
configs:
  init.sh:
    file: ./configs/init.sh
secrets:
  ariadb.env:
    file: ./secrets/mariadb.env
...
services:
  mariadb:
    image: library/mariadb:10.0.23
    entrypoint:
      - /init.sh
    command:
      - /docker-entrypoint.sh
      - mysqld
    configs:
      - source:  init.sh
        target:  /init.sh
        mode:    0500
    secrets:
      - source:  mariadb.env
        target:  /.env
        mode:    0400
    volumes:
      - type:    bind
        source:  /srv/mail/mariadb
        target:  /var/lib/mysql
...
```

Which merges all environment variables into one secret file, instead of have dozens of them.

**Comment by hardware** [comment]
I added some quotes to avoid run.sh script hanging when one of these variables is not defined, it explains why the last build on travis failed.

**Comment by hardware** [comment]
@vizv I like your idea, this is compatible with @amq's `docker secret` method ?

**Comment by vizv** [comment]
@hardware I never tried but I believe it is compatible since it just wrap around the old entrypoint, should work with most (all?) images.

**Comment by hardware** [comment]
@vizv i don't use swarm mode, so i can't test `docker secret`, but you can make a pull request if you want.

**Comment by vizv** [comment]
@hardware I'll do that later this month.

**Pull request merged**
