### PR TITLE
Dkim Update

### LINKED ISSUE #408: dkim/$DOMAIN/private.key is world readable
#### Classification

* [x] Vulnerability

#### Reproducibility

* [X] Always

#### Description
It's all in the subject :D

#### Steps to reproduce
1. `ls -l /var/lib/docker/volumes/mailserver-mailstore/_data/dkim/*/`

#### Expected results
```
-r-------- 1 1024 1024 912 Oct  6 22:23 private.key
-r--r--r-- 1 1024 1024 270 Oct  6 22:23 public.key
```

#### Actual results
```
-r--r--r-- 1 1024 1024 912 Oct  6 22:23 private.key
-r--r--r-- 1 1024 1024 270 Oct  6 22:23 public.key
```

### PR DESCRIPTION
**Pull request by PeerD**
## Description

This PR adds the ability to specify the DKIM selector. If not provided, it falls back to the until now default mail. Also this fixes #408 aswell.

In Addition, the `OPENDKIM_KEY_LENGTH` environment variable has been changed to `DKIM_KEY_LENGTH` to match the new `DKIM_SELECTOR`. For backwards compatibility it falls back to `OPENDKIM_KEY_LENGTH` if not defined (which again defaults to 1024).

With this PR the location of the DKIM keys has changed (with automatic migration). They are in the same folder but are now named selector.private.key and selector.public.key. So its not a breaking change, but if someone is automatically using the keys somewhere else, this might need adjustment to the new key names.

Fixes # (issue)

* Until now the DKIM selector was always mail and could not be changed.
* Now the DKIM selector can be changed and falls back to mail for backwards compatibility

## Type of change
_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Status

- [x] Ready
- [ ] In development
- [ ] Hold

## How has this been tested ?

This has been tested with the (updated) internal test suite.

### CODE REVIEW

**Comment by PeerD** [comment]
Oh, I forgot the following: To be able to restrict access to the DKIM keys, I had to change the dkim folder from vmail to _rspamd user.

**Review by sknight80 — COMMENTED** [review]
LGTM. Quick question, why do we need to add the `selector` part?  I don't have sufficient information about this usage.

**Comment by PeerD** [comment]
The selector is the first part in the DNS txt record used in DKIM: In case of `s1024._domainkey.yourdomain.tld` s1024 would be the selctor, _domainkey is a static keyword defined by DKIM and yourdomain.tld would be your actual domain. The selector is just an arbitary string to define the location of your key. The idea is that you can have multiple keys in multiple txt records and with the selector you tell the target mailserver which key to use.

This can be used e.g. if you have multiple mailservers for one domain, each with their own key. Or if you use a new key, maybe with a larger bitlength, you still want the old key to be accessible, to be able to validate older mails aswell.

So its often recommended to use the date of key creation in your selector, for example like `s20191105` but other examples list `mta1`, `mta2` etc.

Until now this was fixed to `mail` which could not be changed. But this is a completly arbitary decision as there is no "default" or "common" selector.

**Comment by sknight80** [comment]
Awesome! Thank you for the explanation. I am going to approve it.

**Review by sknight80 — APPROVED** [review]

**Pull request closed without merging**
